### PR TITLE
py2 to py3 migration

### PR DESCRIPTION
**Pull request by rakeshgm**
python3 migrations for most of the files have been completed. 
Approvals from all focus groups are needed before merging.

- Send the fix to this branch `wip-nautilus-py3` in case of any issues
- Use teuthology branch: `rh-new` 
- Use suite-branch: `wip-nautilus-py3` or fork based on this branch
- Paste the successfull run logs from each suite. 

Signed-off-by: rakeshgm <rakeshgm@redhat.com>
Signed-off-by: sunilkumarn417 <sunnagar@redhat.com>

### CODE REVIEW

**Comment by rakeshgm** [comment]
`rgw/singleton` pass: http://pulpito.ceph.redhat.com/rakesh-2020-07-04_12:25:09-rgw:singleton-nautilus-distro-basic-clara/

**Comment by rakeshgm** [comment]
`rgw/system`  http://pulpito.ceph.redhat.com/rakesh-2020-07-05_05:00:44-rgw:system-nautilus-distro-basic-clara/ 
failures can ignored. not py3 issue.

**Comment by sunilkumarn417** [comment]
**ceph-ansible single smoke test: PASS** 
http://pulpito.ceph.redhat.com/sunnagar-2020-07-06_04:10:12-smoke:ceph-ansible-master-distro-basic-pluto/

**Comment by rakeshgm** [comment]
`rgw/nfs-ganesha-v2` tests passed: http://pulpito.ceph.redhat.com/rakesh-2020-07-06_02:24:56-rgw:nfs-ganesha-rgw-v2-nautilus-distro-basic-clara/. 

The failures are SELinux related and not related to task.  task execution passed

**Comment by sunilkumarn417** [comment]
`smoke:ceph-volume-lvm` tests passed- http://pulpito.ceph.redhat.com/sunnagar-2020-07-07_02:21:07-smoke:ceph-volume-lvm-master-distro-basic-clara/

**Comment by sunilkumarn417** [comment]
**[ Approved ]** : Deploy and MGMT Focus group.
- **smoke:ceph-volume-lvm tests PASSED** - http://pulpito.ceph.redhat.com/sunnagar-2020-07-07_02:21:07-smoke:ceph-volume-lvm-master-distro-basic-clara/
-  **smoke:ceph-ansible : PASSED**
http://pulpito.ceph.redhat.com/sunnagar-2020-07-06_04:10:12-smoke:ceph-ansible-master-distro-basic-pluto/

**Comment by rakeshgm** [comment]
`rgw/system`, `rgw/singleton`, `rgw/nfs-ganesha-v2` suites passed. some other suites uses ceph-qe-scritps, which are already moved to py3, other suites failures are not related to py3.  so approving from RGW FG. 

**APPROVED**

**Comment by SrinivasaBharath** [comment]
**RADOS**
Tests are passed on following suites-
- **Rados-Basic** - http://pulpito.ceph.redhat.com/skanta-2020-07-13_05:43:29-rados:downstream:basic-wip-nautilus-py3-distro-basic-clara/
-**Rados-Singleton**- http://pulpito.ceph.redhat.com/skanta-2020-07-13_05:45:25-rados:downstream:singleton-wip-nautilus-py3-distro-basic-clara/
 
**Known Issues:**
                The tasks which are cloneing from upstream branch "ceph-nautilus" are failed.Its due to some modules mentioned in the bootstap file are python2 modules  not exist in py3.This up stream branch contains the scripts whcih executes on py2 not on py3.We required to change the brach.

  The task file which contains the ceph-nautilus branch is- 
                       `https://github.com/red-hat-storage/ceph/blob/master/qa/suites/rados/downstream/basic/tasks/rgw_snaps.yaml`
  Upstream  file which is executing on nodes - https://github.com/ceph/s3-tests/blob/ceph-nautilus/bootstrap contains the py2 modules.
  python modules--virtualenv and python-dev

**Review by SrinivasaBharath — APPROVED** [review]

**Comment by harishmunjulur** [comment]
RBD:

Passes runs:
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_13:50:40-rbd:basic-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_15:52:52-rbd:cli-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_16:01:17-rbd:cli_v1-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_17:08:51-rbd:librbd-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_17:09:21-rbd:maintenance-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_18:57:13-rbd:nbd-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_19:00:51-rbd:qemu-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-07_20:42:06-rbd:singleton-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-08_14:06:48-rbd:thrash-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-08_14:07:31-rbd:valgrind-nautilus-distro-basic-argo/
http://pulpito.ceph.redhat.com/hmunjulu-2020-07-09_13:56:20-krbd:rbd-nautilus-distro-basic-argo/

Ignore the failures not py3 issue

**Pull request merged**
