### PR TITLE
adding rgw_multi dir from ceph/ceph:rh-nautilus

### PR DESCRIPTION
**Pull request by rakeshgm**
adding rgw_multi dir from ceph/ceph:rh-nautilus. this is linked to `rgw_multi` under tasks dir. 

Signed-off-by: rakeshgm <rakeshgm@redhat.com>

### CODE REVIEW

**Comment by rakeshgm** [comment]
need to figure out where these tests are being called. until then we dont need any QA tests for these

**Review by TejasC88 — DISMISSED** [review]

**Comment by rakeshgm** [comment]
Suites for this task is in `suites/rgw/multiste` . So adding flag `needs-qa`

**Comment by rakeshgm** [comment]
closing this PR as this is a part of [101](https://github.com/red-hat-storage/ceph/pull/101) which be will later raised to rh-nautilus/master.

**Comment by rakeshgm** [comment]
accidentally closed, this is needed for luminous.

**Pull request closed without merging**
