### PR TITLE
qa/workunits/kernel_untar_build.sh: updating to latest kernel

### PR DESCRIPTION
**Pull request by hkadam134**
Signed-off-by: hkadam134 <hyelloji@redhat.com>

### CODE REVIEW

**Comment by rakeshgm** [comment]
@hkadam134 can you paste the tests run results

**Comment by hkadam134** [comment]
Need a fix for - https://tracker.ceph.com/issues/44537#change-161880 to rerun it.

Had run manually and it worked fine.

**Review by rakeshgm — COMMENTED** [review]
Fix for package issue solved. [1441](https://github.com/ceph/teuthology/pull/1441). 
Can you rerun this test

**Comment by rakeshgm** [comment]
test log: http://pulpito.ceph.redhat.com/hyelloji-2020-04-06_13:58:22-kcephfs-nautilus-distro-basic-clara/370362/

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
