### PR TITLE
Added system tests directory structure & updated RGW test params

### PR DESCRIPTION
**Pull request by sunilkumarn417**
- New system tests directory structure for all ceph interfaces added. 
- Moved RGW tests under `object` dir. 
- Other interfaces tests can be added under each directory under the system-tests directory.
- Creating test scenario tasks and yamls should be as per the test design.     

Signed-off-by: sunilkumarn417 sunnagar@redhat.com

### CODE REVIEW

**Review by rakeshgm — COMMENTED** [review]
can you remove the `yamls` from the directories as there is no valid content? The directory structure can act as a placeholder for other interfaces

**Comment by sunilkumarn417** [comment]
> can you remove the `yamls` from the directories as there is no valid content? The directory structure can act as a placeholder for other interfaces

@rakeshgm removed unwanted files and pushed changes. please review

**Comment by sunilkumarn417** [comment]
http://pulpito.ceph.redhat.com/sunnagar-2020-04-23_15:10:13-system-tests:object:single-site-rh-luminous-distro-basic-clara/

**Comment by rakeshgm** [comment]
Dir structure LGTM.

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
