### PR TITLE
Adding stretch cluster scenarios to downstream

### PR DESCRIPTION
**Pull request by SrinivasaBharath**
# Description

Please include Automation development guidelines. Source of Test case - New Feature/Regression Test/Close loop of customer BZs

# Checklist:

- [x] Create a test case in Polarion reviewed and approved.
- [ ] Create a design/automation approach doc. Optional for tests with similar tests already automated.
- [ ] Review the automation design
- [x] Implement the test script and perform test runs
- [x] Submit PR for code review and approve
- [ ] Update Polarin Test with Automation script details and update automation fields
- [ ] If automation is part of Close loop, update BZ flag qe-test_coverage “+” and link Polarion test

### CODE REVIEW

**Comment by SrinivasaBharath** [comment]
Log files in pulpito-
1.http://pulpito.ceph.redhat.com/skanta-2020-09-26_05:29:42-rados:downstream:singleton-master-distro-basic-clara/
2.http://pulpito.ceph.redhat.com/skanta-2020-09-26_19:31:28-rados:downstream:singleton-master-distro-basic-clara/
3.http://pulpito.ceph.redhat.com/skanta-2020-09-27_04:05:04-rados:downstream:singleton-master-distro-basic-clara/

**Comment by rakeshgm** [comment]
@SrinivasaBharath can you finish the tasks in the checklist, i think this is a new test case right.

**Comment by rakeshgm** [comment]
@SrinivasaBharath any update on the checklist activities.

**Comment by rakeshgm** [comment]
also please squash commits.

**Comment by SrinivasaBharath** [comment]
Polarion Test case- https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83573653
Updated the check list.

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
