### PR TITLE
Added README file for system tests

### PR DESCRIPTION
**Pull request by sunilkumarn417**
Signed-off-by: sunilkumarn417 <sunnagar@redhat.com>

### CODE REVIEW

**Comment by rakeshgm** [comment]
@veera-raghava-reddy we are trying add a small readme file in this folder, can you also review this. if more information is needed, please add your comments, an elaborate document exists in our google docs, this is just to get an overview of what system tests are all about.

**Comment by veera-raghava-reddy** [comment]
> @veera-raghava-reddy we are trying add a small readme file in this folder, can you also review this. if more information is needed, please add your comments, an elaborate document exists in our google docs, this is just to get an overview of what system tests are all about.

**Comment by veera-raghava-reddy** [comment]
Can we have how to run System Test and verifying the results in the readme?

**Comment by veera-raghava-reddy** [comment]
Opening the PR

**Comment by sunilkumarn417** [comment]
> Can we have how to run System Test and verifying the results in the readme?

@veera-raghava-reddy  I will add suite execution info at top level directory README, but would suggest that the verification information or information about test suite could be added at particular test-suite level rather than at top level directory.

**Comment by sunilkumarn417** [comment]
@veera-raghava-reddy updated README file.

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
